---
- block:
  - name: ansible-zabbix-agent | Install Zabbix 3.4 repository on CentOS 7
    yum:
      name: http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-1.el7.centos.noarch.rpm
      state: present

  - name: ansible-zabbix-agent | Install Zabbix Agent package
    yum:
      update_cache: yes
      name: zabbix-agent
      state: present
  when: ansible_distribution_major_version == "7"
