---
- block:
  - name: Instala repositorio Zabbix 3.4 CentOS 7
    yum:
      name: http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-1.el7.centos.noarch.rpm
      state: present

  - name: Instala o pacote zabbix-agent
    yum:
      update_cache: yes
      name: zabbix-agent
      state: present
  when: ansible_distribution_major_version == "7"
